//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajamovdetalle
    {
        public int CajaMovDetalleId { get; set; }
        public int CajaMovId { get; set; }
        public int Cantidad { get; set; }
        public int ConceptoPagoId { get; set; }
        public decimal PU { get; set; }
        public decimal Monto { get; set; }
    
        public virtual cajamov cajamov { get; set; }
        public virtual conceptopago conceptopago { get; set; }
    }
}
