//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajamov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cajamov()
        {
            this.cajamovdetalle = new HashSet<cajamovdetalle>();
        }
    
        public int CajaMovId { get; set; }
        public Nullable<int> CajaDiarioId { get; set; }
        public int PersonaId { get; set; }
        public string Operacion { get; set; }
        public decimal Monto { get; set; }
        public string Glosa { get; set; }
        public bool IndEntrada { get; set; }
        public string Estado { get; set; }
        public int UsuarioRegId { get; set; }
        public System.DateTime FechaReg { get; set; }
        public Nullable<System.DateTime> FechaCobro { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<int> UsuarioDespachoId { get; set; }
        public Nullable<System.DateTime> FechaDespacho { get; set; }
    
        public virtual cajadiario cajadiario { get; set; }
        public virtual persona persona { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajamovdetalle> cajamovdetalle { get; set; }
    }
}
