//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class conceptopago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conceptopago()
        {
            this.cajamovdetalle = new HashSet<cajamovdetalle>();
        }
    
        public int ConceptoPagoId { get; set; }
        public string Denominacion { get; set; }
        public decimal Importe { get; set; }
        public Nullable<int> OficinaId { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajamovdetalle> cajamovdetalle { get; set; }
        public virtual oficina oficina { get; set; }
    }
}
