//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol_menu
    {
        public int Id { get; set; }
        public int RolId { get; set; }
        public int MenuId { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual rol rol { get; set; }
    }
}
